# Site settings
title: ox - 2d canvas game framework
email: jeremy@codevinsky.com
author: Jeremy Dowell
description: "Minimalist 2D game framework made for the web with a strong entity system and modular design. Documentation available and expanding!"
url: "https://codevinsky.github.io/ox"
baseurl: "https://codevinsky.github.io/ox"


#gems: [jekyll-sitemap]
